---
addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - docker-compose build test
  - docker-compose run --rm dep ensure -v

script:
  - docker-compose run --rm test

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin;
    docker build -t myobplatform/shell-operator:$TRAVIS_TAG .;
    docker push myobplatform/shell-operator:$TRAVIS_TAG;
    docker build -t myobplatform/shell-operator:latest .;
    docker push myobplatform/shell-operator:latest;
    fi
