---
version: '2.3'

services:
  go: &base
    build:
      context: .
      target: base
    volumes:
      - ".:/go/src/github.com/MYOB-Technology/shell-operator"
      - "$HOME/.kube:/root/.kube"
    entrypoint: [go]

  dep:
    <<: *base
    entrypoint: [dep]

  sh:
    <<: *base
    entrypoint: [bash]

  test:
    <<: *base
    entrypoint:
      - go
      - test
    command: "./..."

  shoplocal:
    <<: *base
    entrypoint:
      - go
      - run
    command: 
      - main.go
      - -v=4
      - -kubeconfig=/root/.kube/config
      - -shell-config=./shell-config.yaml
      - -logtostderr
