---
boot:
  - command: echo welcome!
watch:
  - apiVersion: v1
    kind: Pod
    command: echo Pod $SHOP_OBJECT_NAME
    concurrency: 5
  - apiVersion: extensions/v1beta1
    kind: Deployment
    command: echo Deployment $SHOP_OBJECT_NAME
    concurrency: 1
  - apiVersion: v1
    kind: Event
    command: echo Event $SHOP_OBJECT_NAME
    concurrency: 10
